webapp:
  container_name: my-webapp
  build: ./webapp/
  ports:
    - "80:80"
    - "433:433"
    - "8000:8000"
    - "8080:8080"
  links:
    - db:db
  volumes:
    - ./webapp:/code
    - /repos:/repos
  env_file: .env

db:
  container_name: my-db
  image: postgres:latest
  ports:
    - "5432:5432"
  env_file: .env
