webapp:
  container_name: my-webapp
  # restart: always
  build: ./webapp/
  ports:
    - "80:80"
    - "433:433"
    - "8000:8000"
    - "8080:8080"
  links:
    - db:db
  volumes:
    - ./webapp:/code
    # - ./repos:/repos
  env_file: .env
   # command: /usr/local/bin/uwsgi --emperor /etc/uwsgi/vassals --uid www-data --gid www-data

db:
  container_name: my-db
  # restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
  env_file: .env
